#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V VI

bspc config border_width         4
bspc config window_gap          16
bspc config window_padding	5
bspc config bottom_padding	9

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color "#2aa198"
bspc config normal_border_color "#002b36"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a surf state=tiled
