#!/bin/bash

# Monitor settings
bspc monitor DP-0 -d 1 2 3 4 5 6
bspc monitor HDMI-0 -d 7 8 9

# Window settings
bspc config border_width 0
bspc config window_gap 0
bspc config bottom_padding 27
bspc config split_ratio 0.50


# Window rules
bspc rule -a '*' monitor=DP-0
bspc rule -a Firefox desktop=^1
bspc rule -a discord desktop=^7
bspc rule -a obs desktop=^8
bspc rule -a Flashplayer state=tiled

## Startup

# Hotkey Daemon
sxhkd &

# Disable CapsLock
xmodmap ~/.Xmodmap

# Fix Cusor On Desktop
xsetroot -cursor_name left_ptr

# Keyboard Colors/Macros
g910-led -a 0000FF
g910-led -gkm 1

# Bar
~/.config/polybar/launch.sh

# Wallpaper
urlpath=$( \
curl "https://www.bing.com/HPImageArchive.aspx?format=rss&idx=0&n=1&mkt=en-US" \
| xmllint --xpath "/rss/channel/item/link/text()" - \
| sed 's/1366x768/1920x1080/g' \
)
curl "https://www.bing.com$urlpath" | feh --bg-fill -

# Compositor
compton -b

# Notifications
dunst &

# Programs
discord &
